baseURL = "https://jeremylongshore.com/"
title = "Jeremy Longshore"
theme = "hugo-bearblog"

[pagination]
pagerSize = 10

[permalinks]
posts = "/posts/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "AI engineering, software, and startup notes."
hideMadeWith = true
# googleAnalytics = "G-XXXXXXX"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30